version: "2"

services:
  test:
    build: .
    restart: "no"
    command: ./test.sh TEST
    volumes:
      - .coverage:/go/src/gitlab.com/nekroze/fluxlog/.coverage
    depends_on:
      - storage

  storage:
    image: influxdb:alpine
    restart: "always"
    volumes:
      - storage:/var/lib/influxdb
    environment:
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_HTTP_LOG_ENABLED: "false"
      INFLUXDB_DATA_QUERY_LOG_ENABLED: "false"

  dashboard:
    image: chronograf:alpine
    command: chronograf --influxdb-url=http://storage:8086
    ports:
      - "8888:8888"
    volumes:
      - dash:/var/lib/chronograf

volumes:
  storage:
  dash:
